### PR TITLE
Cleaning up files for NPL, LBY, URY

### PR DESCRIPTION
**Pull request by ioalexei**
* Converted EPS to PNG for easier use
* Added Nepal RCS website to ReadMe

### CODE REVIEW

**Comment by danbjoseph** [comment]
- I think the folders should keep a vector version of the file. Looks like this PR removes the vector file types from Cruz Roja Uruguaya?
- I think the file names should be cleaned up when editing? For example, `NepalRedCross_logo 1 1.png` would just be `NepalRedCross_logo.png`?

**Comment by ioalexei** [comment]
Good point on file naming, I'll update when I'm back

Re. the vector logos for CR Uruguay, I checked them after seeing [this comment](https://github.com/IFRCGo/logos/issues/7) and it does look like they're wrong. Couldn't find another vector source for them - could try to fix the font on the existing ones if we can get a reliable font id (is it just Arial bold?)

**Comment by danbjoseph** [comment]
If a logo is wrong, that seems like a good reason to remove it! I take back my comment.  Thanks for helping clean up.

**Comment by danbjoseph** [comment]
let me know when you're ready to merge this.

**Comment by ioalexei** [comment]
Cheers Dan - final batch done, all good to merge now.

**Pull request merged**
